## TRAINING AND TESTING SPLIT FOR MODEL

import relevant libraries

In [3]:
import numpy as np
from sklearn.model_selection import train_test_split

GENERATE SOME DATA

In [4]:
a = np.arange(1,101)

In [5]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [6]:
b = np.arange(501,601)

In [7]:
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

## SPLIT THE DATA

In [8]:
train_test_split(a)

[array([  3,  80,  47,  23,  66,  44,   6,  30,  27,   8,  15,  89,  26,
         38,  55,  75,  49,  95,  45,  37,  56,  39,  50,  96,  68,  14,
         64,   7,  94,  54,  91,  93,  58,  34,  92,  11,  77,  31,  74,
         13,   1,  83,  79,  84,  72,  51,  63,  73, 100,  20,  10,  21,
         22,  85,  78,  65,  36,  97,   9,  32,  28,  69,  48,  57,  99,
         59,  98,  90,  29,  82,  18,  41,  46,  19,  81]),
 array([17, 76, 25, 33, 12, 86,  4, 88, 42, 24,  5, 71, 67, 16, 60, 35, 62,
         2, 40, 52, 87, 43, 70, 53, 61])]

In [22]:
a_train , a_test, b_train , b_test = train_test_split(a,b,test_size = 0.2,shuffle = False) # also we can add random_state = 42 or any number 

In [23]:
a_train , a_test

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
        52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
        69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80]),
 array([ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100]))

In [24]:
a_train.shape

(80,)

In [25]:
a_test.shape

(20,)

In [12]:
# we can notice that our data splitted into 75 % and 25 %  , 75% is training data , and 25% is testing data 

In [26]:
b_train

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580])

In [27]:
b_test


array([581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593,
       594, 595, 596, 597, 598, 599, 600])