# Understanding Logistic Regression Tables

Using the same code as in the previous exercise, try to interpret the summary table.

### More information about the dataset: 
Note that <i> interest rate</i> indicates the 3-month interest rate between banks and <i> duration </i> indicates the time since the last contact was made with a given consumer. The <i> previous </i> variable shows whether the last marketing campaign was successful with this customer. The <i>March</i> and <i> May </i> are Boolean variables that account for when the call was made to the specific customer and <i> credit </i> shows if the customer has enough credit to avoid defaulting.

<i> Notes: 
    <li> the first column of the dataset is an index one; </li>
    <li> you don't need the graph for this exercise; </li>
    <li> the dataset used is much bigger </li>
</i>

## Import the relevant libraries

In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns 
sns.set()

import statsmodels.api as sm


## Load the data

Load the ‘Bank_data.csv’ dataset.

In [2]:
DATA = pd.read_csv('Bank_data.csv')

In [3]:
DATA

Unnamed: 0  interest_rate  credit  march  may  previous  duration    y
0             0          1.334     0.0    1.0  0.0       0.0     117.0   no
1             1          0.767     0.0    0.0  2.0       1.0     274.0  yes
2             2          4.858     0.0    1.0  0.0       0.0     167.0   no
3             3          4.120     0.0    0.0  0.0       0.0     686.0  yes
4             4          4.856     0.0    1.0  0.0       0.0     157.0   no
..          ...            ...     ...    ...  ...       ...       ...  ...
513         513          1.334     0.0    1.0  0.0       0.0     204.0   no
514         514          0.861     0.0    0.0  2.0       1.0     806.0  yes
515         515          0.879     0.0    0.0  0.0       0.0     290.0   no
516         516          0.877     0.0    0.0  5.0       1.0     473.0  yes
517         517          4.965     0.0    0.0  0.0       0.0     142.0   no

[518 rows x 8 columns]

In [4]:
DATA = DATA.drop(['Unnamed: 0'], axis = 1)

### Declare the dependent and independent variables

Use 'duration' as the independent variable.

In [5]:
DATA['y'] = DATA['y'].map({'yes':1,'no':0})

In [6]:
X = DATA['duration']
Y = DATA['y']

### Simple Logistic Regression

Run the regression.

In [7]:
X1  = sm.add_constant(X)
reg_log = sm.Logit(Y,X1).fit()
reg_log.summary()
# how can we calculate our LLR value ? LLR = 2*(LL_null - Log-Likelyhood) after that we have to put this value to XSI^2 distribution with value df = 1,because we have only one predictor 
# higher difference it means that predctors predict answer good and model is also good , LL-NUll - grading model withouth prdictors just with intercept
# Log-Likelihood - grade of model with predictors , and that's why the difference between them must be large .
# in this case Pseudo-R^2 - 0.2121 and this is not so large but normal , because good models have 0.4-0.6 

Optimization terminated successfully.
         Current function value: 0.546118
         Iterations 7


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                      y   No. Observations:                  518
Model:                          Logit   Df Residuals:                      516
Method:                           MLE   Df Model:                            1
Date:                Mon, 01 Sep 2025   Pseudo R-squ.:                  0.2121
Time:                        14:39:00   Log-Likelihood:                -282.89
converged:                       True   LL-Null:                       -359.05
Covariance Type:            nonrobust   LLR p-value:                 5.387e-35
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.7001      0.192     -8.863      0.000      -2.076      -1.324
duration       0.0051      0.001      9.159      0.000       0.004       0.006
==============================================================================
"""

### Interpretation

In [8]:
reg_log.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                      y   No. Observations:                  518
Model:                          Logit   Df Residuals:                      516
Method:                           MLE   Df Model:                            1
Date:                Mon, 01 Sep 2025   Pseudo R-squ.:                  0.2121
Time:                        14:39:03   Log-Likelihood:                -282.89
converged:                       True   LL-Null:                       -359.05
Covariance Type:            nonrobust   LLR p-value:                 5.387e-35
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.7001      0.192     -8.863      0.000      -2.076      -1.324
duration       0.0051      0.001      9.159      0.000       0.004       0.006
==============================================================================
"""

In [18]:
reg_log.predict([[-1.7001,500]])

array([0.99570699])

In [19]:
reg_log.predict([[1,500]])

array([0.70182416])

In [20]:
reg_log.predict([[-1.7001,500]])

array([0.99570699])

In [21]:
reg_log.predict([[-1.7001,500]])

array([0.99570699])

In [22]:
reg_log

In [24]:
reg_log.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                      y   No. Observations:                  518
Model:                          Logit   Df Residuals:                      516
Method:                           MLE   Df Model:                            1
Date:                Mon, 04 Aug 2025   Pseudo R-squ.:                  0.2121
Time:                        23:19:55   Log-Likelihood:                -282.89
converged:                       True   LL-Null:                       -359.05
Covariance Type:            nonrobust   LLR p-value:                 5.387e-35
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.7001      0.192     -8.863      0.000      -2.076      -1.324
duration       0.0051      0.001      9.159      0.000       0.004       0.006
==============================================================================
"""

In [9]:
# Pesudo -R^2 аналог R^2 в линейной регресии , можем заметить что значение 0.2121 это обозночает что 21 % изменчивости оутпута Y объясняет предиктор duration а остальные проценты объясняют другие предикоторы

In [10]:
#Log-Lokiely Hodd чем ближе к число 0 тем лучше , в данном случае LL-Null , Log-LikeliHood они связаны между собой LL-Null коэфицеинт правдоподобия без предикторов , получается с предикторами Log-Likelihood меньше это обозноает что предикторы нормально предсказывают выходные данные
# если бы разница между ними была маленькая то это обозночало бы что предиктор особо не влияет на оутпут 